---
# role: openjdk
# file: molecule/resources/playbooks/prepare.yml

- name: OPENJDK | Prepare test instances
  hosts: all
  gather_facts: true
  tasks:
    - name: OPENJDK | Refresh the apt package cache
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts.pkg_mgr == 'apt'
